# Generated by Django 4.0 on 2022-01-05 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('address', models.CharField(max_length=128)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('attraction', 'Attraction'), ('tour', 'Tour')], max_length=64)),
                ('covid_safe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('nightlife', 'Nightlife'), ('sight', 'Sight'), ('landmark', 'Landmark'), ('museum', 'Museum'), ('fun', 'Fun')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('_big_groups', ' Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('multi-day', 'Multi-day'), ('city', 'City'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('hicking', 'Hicking')], max_length=64)),
                ('price', models.SmallIntegerField()),
                ('duration', models.DurationField()),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlanThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan')),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thing_pics')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
    ]
