# Generated by Django 4.0 on 2022-01-12 04:55

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('address', models.CharField(max_length=128)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.CharField(choices=[('attraction', 'Attraction'), ('tour', 'Tour'), ('food', 'Food'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping')], max_length=64)),
                ('covid_safe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('biography', models.TextField(max_length=512, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('nightlife', 'Nightlife'), ('sight', 'Sight'), ('landmark', 'Landmark'), ('museum', 'Museum'), ('fun', 'Fun')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('farmers_market', 'Farmers Market'), ('breweries_and_wine', 'Breweries and Wine'), ('coffee_shop', 'Coffee Shop'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('wildlife_exploration', 'Wildlife Exploration'), ('hiking', 'Hiking'), ('biking', 'Biking'), ('zoos', 'Zoos'), ('river_rafting', 'River Rafting')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('gift_shops', 'Gift Shops'), ('shopping_malls', 'Shopping Malls'), ('antique_stores', 'Antique Stores'), ('department_stores', 'Department Stores'), ('factory_outlets', 'Factory Outlets')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('multi-day', 'Multi-day'), ('city', 'City'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('private', 'Private')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DurationField()),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='PlanThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan')),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thing_pics')),
                ('thing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('posted_on', models.DateField(default=datetime.date(2022, 1, 11))),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
    ]
