# Generated by Django 4.0 on 2022-03-08 09:32

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('address', models.CharField(max_length=128)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.CharField(choices=[('Attraction', 'Attraction'), ('Tour', 'Tour'), ('Food', 'Food'), ('Outdoor', 'Outdoor'), ('Shopping', 'Shopping')], max_length=64)),
                ('covid_safe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('biography', models.TextField(max_length=512, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('Nightlife', 'Nightlife'), ('Sight', 'Sight'), ('Landmark', 'Landmark'), ('Museum', 'Museum'), ('Fun', 'Fun')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('Farmers Market', 'Farmers Market'), ('Breweries and Wine', 'Breweries and Wine'), ('Coffee Shop', 'Coffee Shop'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('Wildlife Exploration', 'Wildlife Exploration'), ('Hiking', 'Hiking'), ('Biking', 'Biking'), ('Zoo', 'Zoo'), ('River Rafting', 'River Rafting')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('Couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('Gift Shop', 'Gift Shop'), ('Shopping Mall', 'Shopping Mall'), ('Antique Store', 'Antique Store'), ('Department Store', 'Department Store'), ('Factory Outlet', 'Factory Outlet')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('Multi-day', 'Multi-day'), ('City', 'City'), ('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Private', 'Private')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.DurationField()),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('is_public', models.BooleanField()),
                ('favorited_by', models.ManyToManyField(related_name='favorited', to='core.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='core.userprofile')),
                ('things', models.ManyToManyField(related_name='plans_in', to='core.Thing')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thing_pics')),
                ('thing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=4096)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5), django.core.validators.MinValueValidator(limit_value=1)])),
                ('posted_on', models.DateField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.userprofile')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.thing')),
            ],
        ),
    ]
