# Generated by Django 4.0 on 2021-12-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='typ',
        ),
        migrations.AddField(
            model_name='attraction',
            name='type',
            field=models.CharField(blank=True, choices=[('nightlife', 'Nightlife'), ('sight', 'Sight'), ('landmark', 'Landmark'), ('museum', 'Museum'), ('fun', 'Fun')], max_length=64),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.CharField(blank=True, choices=[('multi-day', 'Multi-day'), ('city', 'City'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('hicking', 'Hicking')], max_length=64),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='good_for',
            field=models.CharField(choices=[('kids', 'Kids'), ('_big_groups', ' Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='thing',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
