# Generated by Django 4.0 on 2022-01-12 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateField(default=datetime.date(2022, 1, 12)),
        ),
    ]
