# Generated by Django 4.0 on 2021-12-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_attraction_typ_remove_tour_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='type',
            field=models.CharField(choices=[('nightlife', 'Nightlife'), ('sight', 'Sight'), ('landmark', 'Landmark'), ('museum', 'Museum'), ('fun', 'Fun')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('multi-day', 'Multi-day'), ('city', 'City'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('hicking', 'Hicking')], max_length=64),
        ),
    ]
