# Generated by Django 4.0 on 2022-01-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attraction_good_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('farmers_market', 'Farmers Market'), ('breweries_and_wine', 'Breweries and Wine'), ('coffee_shop', 'Coffee Shop'), ('restaurant', 'Restaurant'), ('bar', 'Bar')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Outdoor',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('wildlife_exploration', 'Wildlife Exploration'), ('hiking', 'Hiking'), ('biking', 'Biking'), ('zoos', 'Zoos'), ('river_rafting', 'River Rafting')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('adrenaline_seekers', 'Adrenaline Seekers'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('thing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.thing')),
                ('type', models.CharField(choices=[('gift_shops', 'Gift Shops'), ('shopping_malls', 'Shopping Malls'), ('antique_stores', 'Antique Stores'), ('department_stores', 'Department Stores'), ('factory_outlets', 'Factory Outlets')], max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('good_for', models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('couples', 'Couples')], max_length=64)),
            ],
            bases=('core.thing',),
        ),
        migrations.AlterField(
            model_name='thing',
            name='category',
            field=models.CharField(choices=[('attraction', 'Attraction'), ('tour', 'Tour'), ('food', 'Food'), ('outdoor', 'Outdoor'), ('shopping', 'Shopping')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('multi-day', 'Multi-day'), ('city', 'City'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('private', 'Private')], max_length=64),
        ),
    ]
