# Generated by Django 4.0 on 2022-01-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_is_public_plan_liked_by_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.userprofile'),
        ),
    ]
