# Generated by Django 4.0 on 2022-01-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attraction_type_alter_tour_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='addresss',
            new_name='address',
        ),
    ]
