# Generated by Django 4.0 on 2022-01-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default='Default description', max_length=512),
            preserve_default=False,
        ),
    ]
