# Generated by Django 4.0 on 2022-01-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_food_outdoor_shopping_alter_thing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofileinfo'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.thing'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofileinfo'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='good_for',
            field=models.CharField(choices=[('kids', 'Kids'), ('big_groups', 'Big Groups'), ('a_rainy_day', 'a Rainy Day'), ('couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4096)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofileinfo')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thing')),
            ],
        ),
    ]
