# Generated by Django 4.0 on 2022-01-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planthing',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to='core.plan'),
        ),
    ]
