# Generated by Django 4.0 on 2022-01-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_picture_user_userprofileinfo_bio_alter_picture_thing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='bio',
            new_name='biography',
        ),
    ]
