# Generated by Django 4.0 on 2022-01-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_rename_addresss_thing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thing'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='planthing',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
    ]
