# Generated by Django 4.0 on 2022-01-12 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 6, 0, 0, 392581, tzinfo=utc)),
        ),
    ]
