# Generated by Django 4.0 on 2022-01-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_bio_userprofileinfo_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='Default first_name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='Default last_name', max_length=64),
            preserve_default=False,
        ),
    ]
