# Generated by Django 4.0 on 2022-01-14 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_planthing_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planthing',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thing'),
        ),
    ]
