# Generated by Django 4.0 on 2022-01-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_picture_thing_alter_plan_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(default='One off default'),
            preserve_default=False,
        ),
    ]
