# Generated by Django 4.0 on 2022-01-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_planthing_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='things',
            field=models.ManyToManyField(related_name='plans_in', to='core.Thing'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='core.userprofile'),
        ),
        migrations.DeleteModel(
            name='PlanThing',
        ),
    ]
