# Generated by Django 4.0 on 2022-01-12 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
