# Generated by Django 4.0 on 2022-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_comment_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='good_for',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='type',
            field=models.CharField(choices=[('Nightlife', 'Nightlife'), ('Sight', 'Sight'), ('Landmark', 'Landmark'), ('Museum', 'Museum'), ('Fun', 'Fun')], max_length=64),
        ),
    ]
