# Generated by Django 4.0 on 2022-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attraction_good_for_alter_attraction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='good_for',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Farmers Market', 'Farmers Market'), ('Breweries and Wine', 'Breweries and Wine'), ('Coffee Shop', 'Coffee Shop'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar')], max_length=64),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='good_for',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('Adrenaline Seekers', 'Adrenaline Seekers'), ('Couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='outdoor',
            name='type',
            field=models.CharField(choices=[('Wildlife Exploration', 'Wildlife Exploration'), ('Hiking', 'Hiking'), ('Biking', 'Biking'), ('Zoos', 'Zoos'), ('River Rafting', 'River Rafting')], max_length=64),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='good_for',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Big Groups', 'Big Groups'), ('a Rainy Day', 'a Rainy Day'), ('Couples', 'Couples')], max_length=64),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='type',
            field=models.CharField(choices=[('Gift Shops', 'Gift Shops'), ('Shopping Malls', 'Shopping Malls'), ('Antique Stores', 'Antique Stores'), ('Department Stores', 'Department Stores'), ('Factory Outlets', 'Factory Outlets')], max_length=64),
        ),
        migrations.AlterField(
            model_name='thing',
            name='category',
            field=models.CharField(choices=[('Attraction', 'Attraction'), ('Tour', 'Tour'), ('Food', 'Food'), ('Outdoor', 'Outdoor'), ('Shopping', 'Shopping')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('Multi-day', 'Multi-day'), ('City', 'City'), ('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Private', 'Private')], max_length=64),
        ),
    ]
