# Generated by Django 4.0 on 2022-01-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_title_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
    ]
